name: API_KEY

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - name: Run Convoepersona
        env:
          API_KEY: ${{ secrets.OPENAI_API }} # GitHub Secrets에서 API_KEY 시크릿을 가져옵니다.
        run: python Convoepersona.py
